python test_language_disc.py ^
    --model lavt ^
    --ln_dataset_root ../dataset ^
    --split test ^
    --bert_tokenizer dmis-lab/biobert-base-cased-v1.2 ^
    --ck_bert dmis-lab/biobert-base-cased-v1.2 ^
    --resume ./checkpoints/ln_existBCE_v3_weighted/model_best_lavt_ln_existBCE_v3_2.pth ^
    --swin_type base ^
    --window12 ^
    --img_size 512 ^
    --max_samples 0 ^
    --save_vis ^
    --output_dir ./language_disc_results/v3
